default: build

clean:
	@rm -rf bin

docker-build:
	docker compose -f docker-compose-dev.yml build

docker-up:
	docker compose -f docker-compose-dev.yml up

docker-down:
	docker compose -f docker-compose-dev.yml down